class Node(object):
    def __init__(self, data):
        self.data = data
        self.children = []
    def add_child(self, obj):
        self.children.append(obj)
place = Node("New York")
print(place.data)
p1= Node("Statue of Liberty National Monument\n\ttimings")
p2= Node("Central Park\n\ttimings")
p3= Node("Empire State Building\n\ttimings")
p4= Node("Rockefeller Center\n\ttimings")
p5= Node("The metropolitan Museum of Art\n\ttimings")
p6= Node("Brooklyn Bridge\n\ttimings")
p7= Node("Theater District\n\ttimings")
p8= Node("The High Line\n\ttimings")
p9= Node("Times Square\n\ttimings")
p10= Node("Grand Central Terminal\n\ttimings")
p11= Node("The Museum of Modern Art\n\ttimings")
p12= Node("One world Trade Center\n\ttimings")
p13= Node("Bryant Park\n\ttimings")
p14= Node("Coney Island\n\ttimings")
p15= Node("9/11 Memorial\n\ttimings")
place.add_child(p1)
place.add_child(p2)
place.add_child(p3)
place.add_child(p4)
place.add_child(p5)
place.add_child(p6)
place.add_child(p7)
place.add_child(p8)
place.add_child(p9)
place.add_child(p10)
place.add_child(p11)
place.add_child(p12)
place.add_child(p13)
place.add_child(p14)
place.add_child(p15)
for i in place.children:
    print (i.data)
