class Node(object):
    def __init__(self, data):
        self.data = data
        self.children = []
    def add_child(self, obj):
        self.children.append(obj)
place = Node("Paris,France")
print(place.data)
p1= Node("La Tour Eiffel\n\ttimings")
p2= Node("Louvre Musee\n\ttimings")
p3= Node("Notre Dame Cathedral\n\ttimings")
p4= Node("Bateau Mouche\n\ttimings")
p5= Node("Champs Elysees\n\ttimings")
p6= Node("Montmartre\n\ttimings")
p7= Node("Chateau de Versailles\n\ttimings")
p8= Node("Moulin Rouge\n\ttimings")
p9= Node("Musee d'Orsay\n\ttimings")
p10= Node("Le Marais\n\ttimings")
p11= Node("Palais Garnier\n\ttimings")
p12= Node("Saint Chapelle\n\ttimings")
p13= Node("Pont Neuf\n\ttimings")
p14= Node("La Madeleine\n\ttimings")
p15= Node("Tour Montparnasse\n\ttimings")
place.add_child(p1)
place.add_child(p2)
place.add_child(p3)
place.add_child(p4)
place.add_child(p5)
place.add_child(p6)
place.add_child(p7)
place.add_child(p8)
place.add_child(p9)
place.add_child(p10)
place.add_child(p11)
place.add_child(p12)
place.add_child(p13)
place.add_child(p14)
place.add_child(p15)
for i in place.children:
    print (i.data)
