class Node(object):
    def __init__(self, data):
        self.data = data
        self.children = []
    def add_child(self, obj):
        self.children.append(obj)
place = Node("Port Blair,Andaman Islands")
print(place.data)
p1= Node("cellular jail\n\ttimings")
p2= Node("samudrika marine museum\n\ttimings")
p3= Node("forest museum\n\ttimings")
p4= Node("marina park\n\ttimings")
p5= Node("radhanagar beach\n\ttimings")
p6= Node("jogger's park\n\ttimings")
p7= Node("phoenix bay jetty\n\ttimings")
p8= Node("netaji subhash chandra bose isand\n\ttimings")
p9= Node("viper island\n\ttimings")
p10= Node("chidiya tapu\n\ttimings")
p11= Node("rajiv ghandhi water sports complex\n\ttimings")
p12= Node("elephant beach\n\ttimings")
p13= Node("north bay island\n\ttimings")
p14= Node("wandoor beach\n\ttimings")
p15= Node("rose island\n\ttimings")
place.add_child(p1)
place.add_child(p2)
place.add_child(p3)
place.add_child(p4)
place.add_child(p5)
place.add_child(p6)
place.add_child(p7)
place.add_child(p8)
place.add_child(p9)
place.add_child(p10)
place.add_child(p11)
place.add_child(p12)
place.add_child(p13)
place.add_child(p14)
place.add_child(p15)
for i in place.children:
    print (i.data)
